config:
  send_anonymous_usage_stats: false
jaffle_shop:
  target: dev
  outputs:
    dev:
      dataset: dbt_adam
      fixed_retries: 1
      keyfile: /Users/abh/scratch/dbt-tutorial/dbt-user-creds.json
      location: US
      method: service-account
      priority: interactive
      project: quickstart-1590448450641
      threads: 1
      timeout_seconds: 300
      type: bigquery
sde_dbt_tutorial:
  outputs:
    dev:
      dbname: dbt
      host: localhost
      pass: password1234
      port: 5432
      schema: warehouse
      threads: 1
      type: postgres
      user: dbt
  target: dev
